server:
  port: 8080

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://microservice-product
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
